/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MuscleGainRouteImport } from './routes/muscle-gain'
import { Route as FatLossRouteImport } from './routes/fat-loss'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as IndexRouteImport } from './routes/index'

const MuscleGainRoute = MuscleGainRouteImport.update({
  id: '/muscle-gain',
  path: '/muscle-gain',
  getParentRoute: () => rootRouteImport,
} as any)
const FatLossRoute = FatLossRouteImport.update({
  id: '/fat-loss',
  path: '/fat-loss',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/fat-loss': typeof FatLossRoute
  '/muscle-gain': typeof MuscleGainRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/fat-loss': typeof FatLossRoute
  '/muscle-gain': typeof MuscleGainRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/fat-loss': typeof FatLossRoute
  '/muscle-gain': typeof MuscleGainRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calculator' | '/fat-loss' | '/muscle-gain'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calculator' | '/fat-loss' | '/muscle-gain'
  id: '__root__' | '/' | '/calculator' | '/fat-loss' | '/muscle-gain'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorRoute: typeof CalculatorRoute
  FatLossRoute: typeof FatLossRoute
  MuscleGainRoute: typeof MuscleGainRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/muscle-gain': {
      id: '/muscle-gain'
      path: '/muscle-gain'
      fullPath: '/muscle-gain'
      preLoaderRoute: typeof MuscleGainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fat-loss': {
      id: '/fat-loss'
      path: '/fat-loss'
      fullPath: '/fat-loss'
      preLoaderRoute: typeof FatLossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorRoute: CalculatorRoute,
  FatLossRoute: FatLossRoute,
  MuscleGainRoute: MuscleGainRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
